# Generated by Django 4.2 on 2023-06-24 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
